#!/bin/sh
# ZFS ARC statistics for Linux
# Author alex@trull-dot-org
# Ported by tconnors@rather.puzzling.org
#
#%# family=auto
#%# capabilities=autoconf

sysctl=sysctl
sysctl() {
    path=`echo "$1" | sed 's-\.-/-g ; s-^-/proc/spl/- ; s-misc/--'`
    tail -n +3 $path | awk "{print \"$1.\"\$1\":\", \$3}"
}

case $1 in
    config)
	cat <<EOF
graph_title ZFS ARC Counters - Prefetch
graph_vlabel per second
graph_scale no
graph_category filesystem 
graph_args -l 0
graph_info ZFS ARC Prefetch Counters
EOF
$sysctl kstat.zfs.misc.arcstats | egrep -i Prefetch | awk 'BEGIN { FS = "[.:]" } /hits/ || /miss/ || /hash/ || /deleted/ || /write/ || /evict/  { displayname = $5; gsub("_"," ",displayname) } {print $5".label "displayname"\n"$5".type DERIVE\n"$5".min 0"}' | grep -v "^\."
	exit 0
	;;
    autoconf)
#	if [ ! -x ${sysctl} ]; then
#	    echo "no (${sysctl} is not executable)"
#	    exit 1
#	fi
#	ostype=`uname -s`
#	if [ ${ostype} = "FreeBSD" ]; then
	    echo "yes"
	    exit 0
#	fi
#	echo "no (Your OS is not supported by this plugin)"
#	exit 1
	;;
    suggest)
	exit 0
	;;
esac

$sysctl kstat.zfs.misc.arcstats | egrep -i Prefetch | awk 'BEGIN { FS = "[.:]" } /hits/ || /miss/ || /hash/ || /deleted/ || /write/ || /evict/  { displayname = $5; gsub("_"," ",displayname) } {print $5".value",$NF}' | grep -v "^\."

